version: '3.8'

services:

  db:
    container_name: db
    image: "mysql:latest"
    restart: always
    env_file:
      - db.env

  api:
    container_name: api
    depends_on:
      - db
    restart: always
    env_file:
      - api.env
    build:
      context: .
    ports:
      - "${API_HOST_PORT}:${API_CONTAINER_PORT}"
