spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/aasd?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false"
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  port: 8000
  tomcat:
    max-swallow-size: 100MB

sigma:
  root-url: "/api"
  agents-url: "http://localhost:8002/agents"
  jwt:
    expiration-in-seconds: 3600
