INSERT INTO sigma_api.SIGMA_AUTHORITIES (name)
VALUES ('USER_READ');
INSERT INTO sigma_api.SIGMA_AUTHORITIES (name)
VALUES ('USER_WRITE');
INSERT INTO sigma_api.SIGMA_AUTHORITIES (name)
VALUES ('USER_DELETE');

INSERT INTO sigma_api.SIGMA_AUTHORITIES (name)
VALUES ('OWNER_READ');
INSERT INTO sigma_api.SIGMA_AUTHORITIES (name)
VALUES ('OWNER_WRITE');
INSERT INTO sigma_api.SIGMA_AUTHORITIES (name)
VALUES ('OWNER_DELETE');

INSERT INTO sigma_api.SIGMA_AUTHORITIES (name)
VALUES ('ADMIN_READ');
INSERT INTO sigma_api.SIGMA_AUTHORITIES (name)
VALUES ('ADMIN_WRITE');
INSERT INTO sigma_api.SIGMA_AUTHORITIES (name)
VALUES ('ADMIN_DELETE');